on: [ pull_request ]

env:
  rust_version: 1.51.0

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    name: Compile & Test SDK
    steps:
      - name: check disk usage
        run: df -h
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        name: Cargo Cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            sdk/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_version }}
      - name: check disk usage again
        run: df -h
      - name: Cargo Test
        run: cargo test
        working-directory: sdk
